create table
  marketplace.categories (
    id bigint generated by default as identity,
    uuid uuid null default gen_random_uuid (),
    name text not null,
    constraint categories_pkey primary key (id)
  ) tablespace pg_default;

grant select on table marketplace.categories to service_role;