create table
  marketplace.locations (
    id bigint generated by default as identity,
    uuid uuid not null default gen_random_uuid (),
    name text null,
    constraint locations_pkey primary key (id)
  ) tablespace pg_default;

grant select on table marketplace.locations to service_role;