create table
  marketplace.posts_projection (
    id smallint generated by default as identity,
    uuid uuid not null,
    created_at timestamp with time zone not null,
    title character varying not null,
    description text not null,
    category_id uuid not null default gen_random_uuid (),
    price integer not null,
    location_id uuid not null default gen_random_uuid (),
    user_id character varying not null,
    photo_url text not null,
    is_moderated boolean null default false,
    constraint posts_projection_pkey primary key (id)
  ) tablespace pg_default;


grant all on table marketplace.posts_projection to service_role;