create table
  marketplace.posts_events (
    id bigint generated by default as identity,
    timestamp timestamp without time zone not null,
    "eventType" character varying null,
    "postId" uuid null,
    data json null,
    "postType" text not null default 'Generic'::text,
    constraint posts_events_pkey primary key (id)
  ) tablespace pg_default;



-- Events can be read and inserted, but never modified or deleted.
grant select on table marketplace.posts_events to service_role;
grant insert on table marketplace.posts_events to service_role;