create table "marketplace"."post_comments_projection" (
    "comment_id" uuid not null,
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" uuid not null,
    "commentor_id" uuid not null,
    "comment" text not null,
    "is_seller" boolean not null default false
);


alter table "marketplace"."post_comments_projection" enable row level security;

CREATE UNIQUE INDEX post_comments_projection_pkey ON marketplace.post_comments_projection USING btree (comment_id);

alter table "marketplace"."post_comments_projection" add constraint "post_comments_projection_pkey" PRIMARY KEY using index "post_comments_projection_pkey";

grant all on "marketplace"."post_comments_projection" to "service_role";
