revoke delete on table "moderation"."reports" from "service_role";
revoke insert on table "moderation"."reports" from "service_role";
revoke references on table "moderation"."reports" from "service_role";
revoke select on table "moderation"."reports" from "service_role";
revoke trigger on table "moderation"."reports" from "service_role";
revoke truncate on table "moderation"."reports" from "service_role";
revoke update on table "moderation"."reports" from "service_role";

alter table "moderation"."reports" drop constraint "reports_pkey";

drop index if exists "moderation"."reports_pkey";
drop index if exists "moderation"."reports_ukey";
drop table "moderation"."reports";

create table "moderation"."reported_posts_events" (
    "id" integer generated by default as identity not null,
    "event_type" text not null,
    "post_id" uuid not null,
    "created_at" timestamp with time zone not null,
    "data" json not null
);

CREATE UNIQUE INDEX reported_posts_events_pkey ON moderation.reported_posts_events USING btree (id);

alter table "moderation"."reported_posts_events" add constraint "reported_posts_events_pkey" PRIMARY KEY using index "reported_posts_events_pkey";

grant delete on table "moderation"."reported_posts_events" to "service_role";
grant insert on table "moderation"."reported_posts_events" to "service_role";
grant references on table "moderation"."reported_posts_events" to "service_role";
grant select on table "moderation"."reported_posts_events" to "service_role";
grant trigger on table "moderation"."reported_posts_events" to "service_role";
grant truncate on table "moderation"."reported_posts_events" to "service_role";
grant update on table "moderation"."reported_posts_events" to "service_role";